apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: node-task
  labels:
    learning: ex288
spec:
  description: description here
  displayName: NodeJS Task Execution
  params:
  - name: command
    type: string
    default: npm
  - name: args
    type: string
    default: install
  - name: sourcepath
    type: string
    default: /workspace/output
  steps:
  - name: action
    image: node:20
    workingDir: $(workspaces.workingDir.path)
    script: |
      #!/usr/bin/env bash
      ls -la
      echo "Going into project folder"
      cd $(params.sourcepath)
      ls -la
      echo "in project folder"
      $(params.command) $(params.args)
  workspaces:
    - name: workingDir
      mountPath: /home/node/app
      optional: false

